version: '3'
services:
  web:
    build: ./node
    volumes:
      - "./node/app:/home/app/"
      - "/home/app/node_modules"
    ports:
      - "3030:3000"
    links:
      - mongodb
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./datadb:/data/db
    