version: '3'
services:
  app:
    build: ./backend
    volumes:
      - ./node/app:/home/
      - /usr/src/node_modules
    ports:
      - "3000:3000"
    tty: true
    links:
      - mongodb
    
    
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./datadb:/data/db
    